### PR TITLE
append "errorOutputPattern" property for projects

### PR DESCRIPTION
**Pull request by kyoh86**
To support error log pattern like a `level:(error|warn(ing)?)`

### CODE REVIEW

**Comment by kyoh86** [comment]
```
 +type tools struct {
 +	Fmt, Test, Generate, Vet tool
 +}
 +
 +type tool struct {
 +	status  *bool
 +	cmd     string
 +	options []string
 +	name    string
 +}
 +
 +type Cmds struct {
 +	Vet      bool `yaml:"vet" json:"vet"`
 +	Fmt      bool `yaml:"fmt" json:"fmt"`
 +	Test     bool `yaml:"test" json:"test"`
 +	Generate bool `yaml:"generate" json:"generate"`
 +	Bin      Cmd  `yaml:"bin" json:"bin"`
 +	Build    Cmd  `yaml:"build" json:"build"`
 +	Run      bool `yaml:"run" json:"run"`
 +}
 +
 +// Buildmode options
 +type Cmd struct {
 +	Status bool     `yaml:"status" json:"status"`
 +	Args   []string `yaml:"args,omitempty" json:"args,omitempty"`
  }
```

It's too complicated and nonsense.

Why is that structs same objects with each other??
It MUST be made simple.

**Comment by Asoseil** [comment]
there are a lot of additional options for commands like build(buildmode, compiler) and install. is it a bad idea add the support?

**Comment by Asoseil** [comment]
an option like buildmode could be really important to have for support the new plugin feature

**Comment by kyoh86** [comment]
ok, I got it.

**Pull request merged**
